{{- $portName := include "syntheticapi.portName" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "syntheticapi.fullname" . }}
  namespace: {{ .Values.namespace}}
  labels:
    {{- include "syntheticapi.labels" . | nindent 4 }}
spec:
  replicas: 2
  selector:
    matchLabels:
      {{- include "syntheticapi.selectorLabels" . | nindent 6 }}
  strategy:
    rollingUpdate:
      maxSurge: {{ .Values.strategy.rollingUpdate.maxSurge | default 1 }}
      maxUnavailable: {{ .Values.strategy.rollingUpdate.maxUnavailable | default 1 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "syntheticapi.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "syntheticapi.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: {{ $portName }}
              containerPort: 80
              protocol: TCP
          env:
            {{- toYaml .Values.env | nindent 12 }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}